apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend-app
spec:
  serviceName: frontend-app
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Utilise le SA par défaut, qui sera lié au rôle ci-dessous
      automountServiceAccountToken: true
      containers:
      - name: frontend-container
        # Image avec curl
        image: alpine:latest 
        command: ["sleep", "3600"]