apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend-app
spec:
  serviceName: frontend-app
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Utilise le SA par défaut, qui sera lié au rôle ci-dessous
      automountServiceAccountToken: true
      containers:
      - name: frontend-container
        # Image avec curl
        image: alterway/alpine:websocat
        command: ["sleep", "3600"]
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}    