apiVersion: v1
kind: Pod
metadata:
  name: legacy-internal-db
  labels:
    app: database
    tier: internal
  annotations:
    description: "Pod critique - Ne pas toucher - Contient des données sensibles"
spec:
  containers:
  - name: db-container
    image: busybox
    # Le flag est écrit dans ce fichier au démarrage du pod
    command: ["sh", "-c", "echo 'KUBE{3sc4p3d_Th3_S4ndb0x_Successfully}' > /data/secret_flag.txt && sleep 3600"]
    # Faille de sécurité : Pod privilégié !
    securityContext:
      privileged: true
    volumeMounts:
    - name: data-storage
      mountPath: /data
  volumes:
  - name: data-storage
    emptyDir: {}
  # Assigner au worker node pour garantir sa localisation
  nodeSelector:
    kubernetes.io/hostname: node01