apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-step5
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-step5
  template:
    metadata:
      labels:
        app: nginx-step5
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
        ports:
          - containerPort: 80
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          failureThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    k8s.alterwaylabs.fr: troubleshooting
spec:
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 8020
      targetPort: app
  type: ClusterIP
