apiVersion: v1
kind: Pod
metadata:
  labels:
    run: orange
  name: orange
  namespace: default
spec:
  initContainers:
  - name: init-orange
    image: busybox
    command:
    - sh
    - -c
    - 'sleeeeeep 3'
  containers:
  - command:
    - sh 
    - -c 
    - | 
      echo the app is running && sleep 3600
    image: busybox:1.28
    name: orange-container