apiVersion: v1
kind: Pod
metadata:
  labels:
    run: super-user-pod
  name: super-user-pod
  namespace: default
spec:
  containers:
  - name: super-user-pod
    image: busybox:1.28
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]
    securityContext:
      capabilities:
        add: ["SYS_TIME"]