apiVersion: v1
kind: Pod
metadata:
  labels:
    run: use-pv
  name: use-pv
  namespace: default
spec:
  containers:
    - name: use-pv
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: myvol
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: my-pvc-claim